# Generated by Django 5.0.3 on 2024-05-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='listened',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
