# Generated by Django 5.0.3 on 2024-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='like',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
